version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file:
      - minio.env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  
