version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  
