# Generated by Django 5.0 on 2023-12-09 17:56

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше нуля или равнятся нулю')], verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'db_table': 'achive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('course_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Диапозон должен быть в диапозоне от 0 до 2'), django.core.validators.MaxValueValidator(2, message='Диапозон должен быть в диапозоне от 0 до 2')], verbose_name='Сложность [0;2]')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='Почта')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(6, 'Возраст должнен быть от 6 до 100'), django.core.validators.MaxValueValidator(100, 'Возраст должнен быть от 6 до 100')], verbose_name='Возраст')),
                ('refresh', models.CharField(max_length=100, verbose_name='Рефреш')),
                ('total_points', models.IntegerField(verbose_name='Общее кол-во очков')),
                ('final_exam_current', models.IntegerField(verbose_name='Текущий бал за тест')),
                ('final_exam_max', models.IntegerField(verbose_name='Лучшее решение теста')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок годности токена')),
                ('registration_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Финальный тест',
                'verbose_name_plural': 'Финальный тест',
                'db_table': 'final_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст ответа')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Финал -> answer',
                'verbose_name_plural': 'Финал -> answer',
                'db_table': 'final_test_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Финал -> question',
                'verbose_name_plural': 'Финал -> question',
                'db_table': 'final_test_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestQuestionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Финал -> direction',
                'verbose_name_plural': 'Финал -> direction',
                'db_table': 'final_test_question_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('forward_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вид угрозы',
                'verbose_name_plural': 'Виды угроз',
                'db_table': 'forward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForwardSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Угроза -> media',
                'verbose_name_plural': 'Угроза -> media',
                'db_table': 'forward_src',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Кол-во поинтов за курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('lesson_text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Урок -> material',
                'verbose_name_plural': 'Урок -> material',
                'db_table': 'lesson_mat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonMatSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Урок -> media',
                'verbose_name_plural': 'Урок -> media',
                'db_table': 'lesson_mat_src',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('lesson_text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Урок -> test',
                'verbose_name_plural': 'Урок -> test',
                'db_table': 'lesson_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст ответа')),
                ('correct', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Тест -> answer',
                'verbose_name_plural': 'Тест -> answer',
                'db_table': 'lesson_test_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTestAnswerSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Ответ -> media',
                'verbose_name_plural': 'Ответ -> media',
                'db_table': 'lesson_test_answer_src',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Тест -> question',
                'verbose_name_plural': 'Тест -> question',
                'db_table': 'lesson_test_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTestQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид вопроса',
                'verbose_name_plural': 'Виды вопросов',
                'db_table': 'lesson_test_question_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип урока',
                'verbose_name_plural': 'Типы уроков',
                'db_table': 'lesson_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('news_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('creation_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('url_image', models.CharField(max_length=255)),
                ('url_video', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть отрицательной')], verbose_name='Цена')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Юзер-Достижение',
                'verbose_name_plural': 'Юзер-Достижение',
                'db_table': 'user_achive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Максимальный результат')),
                ('last_result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Последний резульатт')),
            ],
            options={
                'verbose_name': 'Юзер -> финал',
                'verbose_name_plural': 'Юзер -> финал',
                'db_table': 'user_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Юзер-Урок',
                'verbose_name_plural': 'Юзер-Урок',
                'db_table': 'user_lesson',
                'managed': False,
            },
        ),
    ]
