# Generated by Django 5.0 on 2023-12-09 09:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('news_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('url_image', models.CharField(max_length=255)),
                ('url_video', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='userachieve',
            table='user_achive',
        ),
    ]
