# Generated by Django 5.0 on 2023-12-09 14:40

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_news_alter_userachieve_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Финальный тест',
                'verbose_name_plural': 'Финальный тест',
                'db_table': 'final_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст ответа')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Финал -> answer',
                'verbose_name_plural': 'Финал -> answer',
                'db_table': 'final_test_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Финал -> question',
                'verbose_name_plural': 'Финал -> question',
                'db_table': 'final_test_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalTestQuestionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Финал -> direction',
                'verbose_name_plural': 'Финал -> direction',
                'db_table': 'final_test_question_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Максимальный результат')),
                ('last_result', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Последний резульатт')),
            ],
            options={
                'verbose_name': 'Юзер -> финал',
                'verbose_name_plural': 'Юзер -> финал',
                'db_table': 'user_final',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False, 'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
