# Generated by Django 5.0 on 2023-12-08 17:50

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0003_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('course_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Диапозон должен быть в диапозоне от 0 до 2'), django.core.validators.MaxValueValidator(2, message='Диапозон должен быть в диапозоне от 0 до 2')], verbose_name='Возраст')),
                ('value', models.IntegerField(verbose_name='Кол-во поинтов за курс')),
                ('url', models.CharField(max_length=255, verbose_name='S3 картинка')),
            ],
            options={
                'verbose_name': 'Курсы',
            },
        ),
    ]
