# Generated by Django 5.0 on 2023-12-08 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0005_lessontype_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Диапозон должен быть в диапозоне от 0 до 2'), django.core.validators.MaxValueValidator(2, message='Диапозон должен быть в диапозоне от 0 до 2')], verbose_name='Сложность [0;2]'),
        ),
        migrations.AlterField(
            model_name='course',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Кол-во поинтов за курс'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение должно быть больше или равно 0')], verbose_name='Кол-во поинтов за курс')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.course', verbose_name='Курс')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.lessontype', verbose_name='Тип урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('finish', models.BooleanField(default=False)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminka.lesson', verbose_name='Урок')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Юзер-Урок',
                'verbose_name_plural': 'Юзер-Урок',
            },
        ),
    ]
